CREATE TABLE STELLENANGEBOTE(
    ID INT NOT NULL AUTO_INCREMENT,
    UNTERNEHMEN INT NOT NULL,
    TITLE VARCHAR(150) NOT NULL,
    POSITION VARCHAR(100) NOT NULL,
    BESCHREIBUNG TEXT NOT NULL,
    PRIMARY KEY(ID)
);
